title: cyrilsch's blog
author: cyrilsch
email: 56317190+cyrilsch@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  cyrilsch's personal coding blog 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  cyrilsch # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
